name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  Build:
    env:
      TAG_NAME: "v1.1.4"
    runs-on: ubuntu-latest

    steps:
    #拉取代码建立Docker镜像
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
      docker build . --file Dockerfile --tag dyp1docker/izone_web:$TAG_NAME
    - name: Login to Registry
      run : docker login --username=${{ secrets.DOCKER_USERNAME  }} --password ${{ secrets.DOCKER_PASSWORD }}
    - NAME: Push Image
      run: |
        docker push dyp1docker/izone_web:$TAG_NAME

